[build]
  command = "npm run netlify:build"
  functions = "lambda"
  publish = "__sapper__/export"
  environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs10.x" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200