[build]
  command = "npm run netlify:build"
  publish = "__sapper__/export"
  environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs10.x" }

# [[redirects]]
#   from = "/api/*"
#   to = "https://barnsworthburning-api.netlify.com/.netlify/functions/:splat"
#   status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
