const spaces = {
	understanding: 'recl7fmNTA8ZCTMIO',
	architecture: 'rec3CNAqkaUQAA5vR',
	information: 'recmIU63o3TQ4iToK',
	constraints: 'recIKwx4l64A2qzyf',
	creativity: 'recoJzT3SLYBASI6W',
	teaching: 'recEWApPDsOcyCQzP',
	// thinking: 'recTzKGH68OowoPdC',
	// learning: 'recmLtItf40HIEJDN',
	// planning: 'recKQ03VSZGPQTmR2',
	// business: 'recmsoqhqG9FEzNvI',
	// geometry: 'recwvu09meIdciRrS',
	// systems: 'recj25JTG7leVWkPP',
	// writing: 'reca3zUPxXxgFJUjo',
	// meaning: 'recQ9kzuqrrd4Hn2E',
	// sadness: 'recfcoKCeI3vJuSgk',
	// beauty: 'recmpNYmegUZV4gs9',
	// nature: 'recVZe8vC0BVJhhml',
	// seeing: 'recdBSUuW5Pc88sOK',
	// design: 'rec4aBg6st11eTMJZ',
	// craft: 'recDvJSnmNFJSVLln',
	// tools: 'recep6vYPYyDej1Ku',
	// color: 'recDbaO5mtyYdsKHz',
	// words: 'recPLjuLVRiU5b9j2',
	// death: 'recwvwRT0fLXfevtk',
	// work: 'recE9RuIn1HdYGsWy',
	// code: 'recu0luvkJFAQKofO',
	// type: 'rec9AN7zKnQM3TKV8',
	// food: 'recV03AgFTVchWtM2',
	time: 'rec7MhkGLirgzgXyy',
	love: 'recnaxWPwoEOT4AvA',
	life: 'recli7239gzLsn6X0',
	zen: 'recWGrLIpZ76ukHOu',
	art: 'recobaTECu4zjey6Q',
	ux: 'recqFjmep8jmBRgGx',
	i: 'recvaDhnPGrkA1yi0'
};

export default spaces;
