const spaces = {
	understanding: 'recl7fmNTA8ZCTMIO',
	architecture: 'rec3CNAqkaUQAA5vR',
	creativity: 'recoJzT3SLYBASI6W',
	melancholy: 'recfcoKCeI3vJuSgk',
	aesthetics: 'recrYf0OvtSXhB9sf',
	material: 'recOHsNfurhNjKeuS',
	identity: 'recuRoZ5pF6J2cqEr',
	teaching: 'recEWApPDsOcyCQzP',
	planning: 'recKQ03VSZGPQTmR2',
	function: 'recnDstnk3xyyrdWy',
	meaning: 'recQ9kzuqrrd4Hn2E',
	memory: 'receOiaWQiLs3fZUH',
	beauty: 'recmpNYmegUZV4gs9',
	nature: 'recVZe8vC0BVJhhml',
	seeing: 'recdBSUuW5Pc88sOK',
	design: 'rec4aBg6st11eTMJZ',
	making: 'rect3bxOTNR53RLd8',
	craft: 'recDvJSnmNFJSVLln',
	color: 'recDbaO5mtyYdsKHz',
	words: 'recPLjuLVRiU5b9j2',
	death: 'recwvwRT0fLXfevtk',
	work: 'recE9RuIn1HdYGsWy',
	time: 'rec7MhkGLirgzgXyy',
	life: 'recli7239gzLsn6X0',
	art: 'recobaTECu4zjey6Q',
	zen: 'recWGrLIpZ76ukHOu',
	ux: 'recqFjmep8jmBRgGx',
	i: 'recvaDhnPGrkA1yi0',
};

export default spaces;
